# Generated by Django 5.1.5 on 2025-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='csv_model_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='csv_upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
