# Generated by Django 5.1.5 on 2025-02-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_user_csv_model_data_user_csv_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='csv_model_data',
        ),
        migrations.AddField(
            model_name='user',
            name='keras_model_path',
            field=models.CharField(default='cnn/modelV2_full.keras', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='predictions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='csv_data',
            field=models.FileField(blank=True, null=True, upload_to='csv_uploads/'),
        ),
    ]
