# Generated by Django 5.1.5 on 2025-02-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_remove_user_csv_model_data_user_keras_model_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keras_model_path',
            field=models.CharField(default='modelV2_full.keras', max_length=255),
        ),
    ]
