# Generated by Django 4.2.19 on 2025-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_alter_user_keras_model_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keras_model_path',
            field=models.CharField(default='./modelV2Class_full.keras', max_length=255),
        ),
    ]
